services:
  db:
    image: postgres:16  # CAMBIO 1: Forzamos la 16. La "latest" no admite tu línea de volúmenes de abajo.
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # CAMBIO 2: Tu Dockerfile usa "/app", si aquí pones "/code", Django no verá tus archivos.
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - MAILEROO_API_KEY=a0a8621916188433006076433647ba766bb49843b6334ca03afd518f441c1dec
      - MAILEROO_DOMAIN_ID=test@d461399e50cd3a07.maileroo.org
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"