"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-59xd87n6cf#i_s86^%i&(*_0dw$%#biedaip*hzoki$z!@85ll'

# =================================================================
# CORRECCIONES CLAVE PARA EL DESARROLLO
# =================================================================

# 1. ESTABLECER DEBUG A TRUE (Muestra errores detallados y relaja restricciones)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 2. CONFIGURAR HOSTS PERMITIDOS (Para evitar errores 400)
# Cuando DEBUG = True, Django acepta peticiones de 127.0.0.1 y localhost automáticamente.
# Pero incluirlos explícitamente evita problemas con algunas configuraciones.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# =================================================================
# CONFIGURACIONES DE APLICACIONES Y MIDDLEWARE
# =================================================================

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'florafestival', # Nuestra aplicación
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Está correcto, las plantillas se buscan dentro de las apps
        'APP_DIRS': True, # Esto es esencial para buscar en florafestival/templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# =================================================================
# CONFIGURACIONES DE BASE DE DATOS Y VALIDACIÓN
# =================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# ... (dejar intacto) ...
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =================================================================
# CONFIGURACIONES DE ESTATICOS E INTERNACIONALIZACIÓN
# =================================================================

# Internationalization
# ... (dejar intacto) ...
LANGUAGE_CODE = 'es-es' # RECOMENDACIÓN: Usar español si tu app es para Córdoba/España
TIME_ZONE = 'Europe/Madrid' # RECOMENDACIÓN: Usar la zona horaria correcta

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static", # Esto busca la carpeta /static en la raíz del proyecto
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'