# Generated by Django 5.2.7 on 2025-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('organizador', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=30)),
                ('dotacion_economica', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('edicion', models.PositiveIntegerField(blank=True, help_text='Número de edición del premio', null=True)),
                ('ambito', models.CharField(choices=[('internacional', 'Internacional'), ('nacional', 'Nacional')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('pagina_oficial', models.URLField(blank=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nombre', 'anio'), name='unique_premio_anio')],
            },
        ),
    ]
