name: Django CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 2DAW/DWEntornoServidor/steamlike_backend

    steps:
    - uses: actions/checkout@v4 # Descarga tu código

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Instala dependencias

    - name: Run Tests
      run: |
        python manage.py test # Ejecuta los tests del backend