name: Django CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    # Se ejecuta si es un push normal, o si eliges 'test' o 'both' manualmente
    if: github.event_name == 'push' || github.event.inputs.action == 'test' || github.event.inputs.action == 'both'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 2DAW/DWEntornoServidor/steamlike_backend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage # Necesario para el Ejercicio 4

    - name: Run Tests with Coverage
      run: |
        # Ejecuta tests con métrica de cobertura para el Ejercicio 4
        coverage run manage.py test
        coverage report 

  deploy:
    # Solo se ejecuta si lo eliges manualmente ('deploy' o 'both')
    if: github.event.inputs.action == 'deploy' || github.event.inputs.action == 'both'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Render
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}